# Generated by Django 3.2.7 on 2021-11-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_comment_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
